export { LoginPage } from './auth/LoginPage';
export { RegisterPage } from './auth/RegisterPage';
export { QuestionnairePage } from './questionnaires/QuestionnairePage';
export { EducationPage } from './education/EducationPage';
export { ComplaintsPage } from './complaints/ComplaintsPage';
export { HomePage } from './home/HomePage';
export { PlaceholderPage } from './placeholder/PlaceholderPage';
export { ProtocolsPage } from './protocols/Protocols';
export { NewsPage } from './news/newsPage';
